kind: Service
apiVersion: v1
metadata:
  name: spring-mongo-service
spec:
  selector:
    app: spring-mongo-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30609
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mongo-service
spec:
  selector:
    matchLabels:
      app: spring-mongo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-mongo-service
    spec:
      containers:
        - name: spring-mongo-service
          image: zydiii/spring-mongo-service:1.6
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_name
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
